'use client';
import { FaLaptopCode, FaGithub, FaLinkedin } from "react-icons/fa";
import { FiCoffee } from "react-icons/fi";
import { IoIosMail } from "react-icons/io";
import { IoShareSocial } from "react-icons/io5";
import Image from 'next/image';

import * as THREE from 'three'
import React, { Suspense, useRef } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import { Html, Environment, useGLTF, ContactShadows, OrbitControls } from '@react-three/drei'
import WebPage from './WebPage'

function Laptop() {
  const group = useRef<THREE.Mesh>(null)
  // Load model
  const { nodes, materials } = useGLTF('/mac-draco.glb')
  // Make it float
  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    if (group.current) {
      group.current.rotation.x = THREE.MathUtils.lerp(group.current.rotation.x, Math.cos(t / 2) / 20 + 0.25, 0.1)
      group.current.rotation.y = THREE.MathUtils.lerp(group.current.rotation.y, Math.sin(t / 4) / 20, 0.1)
      group.current.rotation.z = THREE.MathUtils.lerp(group.current.rotation.z, Math.sin(t / 8) / 20, 0.1)
      group.current.position.y = THREE.MathUtils.lerp(group.current.position.y, (-2 + Math.sin(t / 2)) / 2, 0.1)
    }
  })
  // The jsx graph was auto-generated by: https://github.com/pmndrs/gltfjsx
  return (
    <group ref={group} dispose={null}>
      <group rotation-x={-0.425} position={[0, -0.04, 0.41]}>
        <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials.aluminium} geometry={(nodes['Cube008'] as THREE.Mesh).geometry} />
          <mesh material={materials['matte.001']} geometry={(nodes['Cube008_1'] as THREE.Mesh).geometry} />
          <mesh geometry={(nodes['Cube008_2'] as THREE.Mesh).geometry}>
            <Html className="content" rotation-x={-Math.PI / 2} position={[0, 0.05, -0.09]} transform occlude>
              <div className="wrapper">
                <WebPage />
              </div>
            </Html>
          </mesh>
        </group>
      </group>
      <mesh material={materials.keys} geometry={(nodes.keyboard as THREE.Mesh).geometry} position={[1.79, 0, 3.45]} />
      <group position={[0, -0.1, 3.39]}>
        <mesh material={materials.aluminium} geometry={(nodes['Cube002'] as THREE.Mesh).geometry} />
        <mesh material={materials.trackpad} geometry={(nodes['Cube002_1'] as THREE.Mesh).geometry} />
      </group>
      <mesh material={materials.touchbar} geometry={(nodes.touchbar as THREE.Mesh).geometry} position={[0, -0.03, 1.2]} />
    </group>
  )
}

export default function Home() {
  return (
    <div>
      <div className="flex flex-col m-auto max-w-5xl items-center justify-center">
        <div className="flex flex-col sm:flex-row gap-4 w-full">
          <div style={{ width: '100%', height: '40vh' }} className="flex w-full m-auto items-center justify-center">
            <Canvas camera={{ position: [0, 0, -15], fov: 55 }}>
              <pointLight position={[10, 10, 10]} intensity={1.5} />
              <Suspense fallback={null}>
                <group rotation={[0, Math.PI, 0]} position={[0, 1, 0]}>
                  <Laptop />
                </group>
                <Environment preset="city" />
              </Suspense>
              <ContactShadows position={[0, -3, 0]} scale={20} blur={2} far={4.5} />
              <OrbitControls enablePan={false} enableZoom={false} minPolarAngle={Math.PI / 2.2} maxPolarAngle={Math.PI / 2.2} />
            </Canvas>
          </div>
          <div className="w-full m-auto p-2">
            <Image height={'300'} width={'300'} alt="Profile Picture" src="/profile.jpg" className="m-auto rounded-4xl border-2 border-(--background)" />
          </div>
        </div>
        <div className="flex flex-col gap-2 p-2">
          <div className="flex flex-col m-auto mb-6">
            <p className="text-xl p-2 m-auto flex bg-(--background) rounded-sm mb-1">Life&nbsp;
              <FiCoffee className="flex mt-auto mb-auto" />
            </p>
            <p className="p-2 m-auto flex bg-(--background) rounded-sm">
              I was raised in Texas, but moved Northeast after high school. I&apos;m married to the light of my life, and have a cat named Nylah. I attained my Bachelors of Science in Computer Science and Cybersecurity from Liberty University in 2025.
            </p>
          </div>
          <div className="flex flex-col m-auto mb-6">
            <p className="text-xl p-2 m-auto flex bg-(--background) rounded-sm mb-1">Work&nbsp;
              <FaLaptopCode className="flex mt-auto mb-auto" />
            </p>
            <p className="p-2 m-auto flex bg-(--background) rounded-sm">
              I&apos;m currently a Service Desk Technician III where I work on large projects and collaborate across teams. I&apos;m looking to move into software engineering work.
            </p>
          </div>
          <div className="flex flex-col m-auto mb-6">
            <p className="text-xl p-2 m-auto flex bg-(--background) rounded-sm mb-1">Contact&nbsp;
              <IoIosMail className="flex mt-auto mb-auto" />
            </p>
            <p className="p-2 m-auto flex bg-(--background) rounded-sm">
              Email:&nbsp;<a className="text-(--text-accent)" href="mailto:jpatrick5402@gmail.com">jpatrick5402@gmail.com</a>
            </p>
          </div>
          <div className="flex flex-col m-auto mb-6">
            <p className="text-xl p-2 m-auto flex bg-(--background) rounded-sm mb-1">Socials&nbsp;
              <IoShareSocial className="flex mt-auto mb-auto" />
            </p>
            <p className="p-2 m-auto flex bg-(--background) rounded-sm gap-2 text-2xl">
              <a href="https://github.com/jpatrick5402/"><FaGithub /></a>
              <a href="https://www.linkedin.com/in/joseph-patrick-b84990238/"><FaLinkedin /></a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
